# Updates {-}

In het overzicht hier onder worden de belangrijkste wijzigingen die zijn aangebracht in deze online versie ten opzicht van [de originele publicatie uit 2019](https://oar.onroerenderfgoed.be/item/5241) opgesomd in chronologische volgorde.
<br/>
<br/>


#### 1.0.0 (15-09-2020)


- Handleiding ***^14^C: dateren met radiokoolstof*** online te raadplegen op <https://hanecakr.github.io/handleidingRadiokoolstof/>, zoals gepubliceerd door K. Haneca, A. Ervynck en M. Van Strydonck in 2019.


#### 1.1.0 (21-09-2020)

- Aanpassingen aangebracht in het hoofdstuk 'Kalibratie' naar aanleiding van de publicatie van de nieuwe kalibratiecurve **IntCal20**.
- Ook in de [Handleiding OxCal](#Oxcal) werden figuren aangepast waar nodig en Bayesiaanse modellen opnieuw berekend met de nieuwste versie van OxCal (v4.4) en de IntCal20 kalibratiecurve.
- De code die nodig is om de kalibraties uit te voeren of de Bayesiaanse modellen te berekenen uit de [Handleiding OxCal](#Oxcal), werd toegevoegd aan elke figuur. Deze code kan gekopieerd worden naar een nieuw OxCal-project om dezelfde analyse te herhalen.


#### 1.2.0 (24-09-2020)

- Extra paragraaf toegevoegd over dateren met behulp van de _bomb peak_ in het hoofdstuk [Kalibratie](#kalibratie).
- Extra paragraaf over de C/N-verhouding (als maat voor mogelijke contaminatie), %C en %N (als maat voor degradatie en conditie) bij botmateriaal, in het hoofdstuk [Rapporteren](#rapporteren).
- Youtube-video van "Universiteit van Vlaanderen" over het principe van een radiokoolstofdatering toegevoegd aan de inleiding.
- Korte paragraaf toegevoegd over _Kernel Density Estimates (KDE)_ aan 'Gesommeerde probabiliteiten' in het hoofdstuk [Bayesiaanse analyses](#modelleren).


#### 1.2.1 (24-11-2020)

- Extra figuren in het hoofdstuk [Kalibratie](#kalibratie) i.v.m. de **IntCal20** kalibratiecurve (vergelijking met oudere curves en resolutie).


#### 1.2.2 (12-01-2022)

- Nieuwe layout (bootstrap4 template).


#### 1.2.3 (14-10-2022)

- Achterliggende OxCal-code toegevoegd aan '8 - Handleiding OxCal'.
- Animaties verval $\mathrm{^{14}C}$ atomen en kalibratie toegevoegd (met dank aan &copy; [Maarten Blaauw](https://maarten14c.github.io/)).
  

#### 1.2.4 (02-09-2024)

- Omschakelen van [`bookdown`](https://bookdown.org/) naar [`quarto`](https://quarto.org/).
- Integratie [`lightbox`](https://quarto.org/docs/output-formats/html-lightbox-figures.html) voor figuren.


#### 1.3.0 (09-09-2024)

- Actualisatie handleiding.
- Hoofdstuk 8 aangepast naar nieuwe interface OxCal 4.4.
- Toevoegingen in hoofdstuk 'kalibratie' (3.4), 'onderzoeksvragen' (4.1) en 'bibliografie'.